In [1]:
import numpy as np
from numpy import linalg as LA
import matplotlib.pyplot as plt

In [2]:
def create_stiffness_matrix(k_values):
    '''剛性マトリックス作成'''

    n = len(k_values) - 1
    k = np.zeros((n, n))

    for i in range(n):
        k[i, i] = k_values[i] + k_values[i + 1]
        if i < n - 1:
            k[i, i + 1] = -k_values[i + 1]
            k[i + 1, i] = -k_values[i + 1]

    return k

In [27]:
m_values = [1, 2]
k_values = [10000, 10000, 10000]
f_value = [3, 1]

In [28]:
mass_matrix = np.diag(m_values)
stiffness_martix = create_stiffness_matrix(k_values)
force_vector = np.array(f_value)
mass_matrix, stiffness_martix, force_vector

(array([[1, 0],
        [0, 2]]),
 array([[ 20000., -10000.],
        [-10000.,  20000.]]),
 array([3, 1]))

In [29]:
mass_matrix_inv = np.linalg.inv(mass_matrix)
eigenvalues, eigenvectors = LA.eig(np.dot(mass_matrix_inv, stiffness_martix))
eigenvalues, eigenvectors

(array([23660.25403784,  6339.74596216]),
 array([[ 0.9390708 ,  0.59069049],
        [-0.34372377,  0.80689822]]))

In [30]:
# 固有値の順番を昇順にソート
eigenvalues_sort = np.sort(eigenvalues)
 
# 固有値のソート時のインデックスを取得
# ⇒固有ベクトルと対応させるため
sort_index = np.argsort(eigenvalues)
 
# 固有値に対応する固有ベクトルをソート
eigenvectors_sort = []
for i in range(len(sort_index)):
    eigenvectors_sort.append(eigenvectors.T[sort_index[i]])
eigenvectors_sort = np.array(eigenvectors_sort)
 
# 結果をコンソールに表示
print(np.sqrt(eigenvalues_sort))
print(eigenvectors_sort)

[ 79.6225217  153.81890013]
[[ 0.59069049  0.80689822]
 [ 0.9390708  -0.34372377]]


In [22]:
eigen_mode_matrix = eigenvectors_sort.T
eigen_mode_matrix

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [9]:
modal_mass_matrix = np.dot(eigen_mode_matrix.T, np.dot(mass_matrix, eigen_mode_matrix))
modal_stiffness_matrix = np.dot(eigen_mode_matrix.T, np.dot(stiffness_martix, eigen_mode_matrix))
modal_force_vector = np.dot(eigen_mode_matrix.T, force_vector)
modal_mass_matrix, modal_stiffness_matrix, modal_force_vector

(array([[1., 0.],
        [0., 1.]]),
 array([[ 1.00000000e+01, -1.77635684e-15],
        [-8.88178420e-16,  3.00000000e+01]]),
 array([2.82842712, 1.41421356]))

In [11]:
modal_mass_1, modal_mass_2 = modal_mass_matrix[0][0], modal_mass_matrix[1][1]
modal_stiffness_1, modal_stiffness_2 = modal_stiffness_matrix[0][0], modal_stiffness_matrix[1][1]
modal_force_1, modal_force_2 = modal_force_vector
modal_mass_1, modal_mass_2, modal_stiffness_1, modal_stiffness_2, modal_force_1, modal_force_2

(1.0, 1.0, 10.0, 30.0, 2.82842712474619, 1.4142135623730954)

In [32]:
1E-09

1e-09