$$
\begin{bmatrix}
m_1 & 0 \\ 0 & m_2
\end{bmatrix} 
\begin{Bmatrix}
\ddot{x}_1 \\ \ddot{x}_2
\end{Bmatrix} + 
\begin{bmatrix}
k_1 + k_2 & -k_2 \\ -k_2 & k_2 + k_3
\end{bmatrix}
\begin{Bmatrix}
{x}_1 \\ {x}_2
\end{Bmatrix} =
\begin{Bmatrix}
0 \\ 0
\end{Bmatrix}
$$
$$ \bold{M}\bold{\ddot{x}} + \bold{K}\bold{{x}} = 0 $$
$$ [-\omega^2\bold{M} + \bold{K}]\bold{u} = 0 $$

In [208]:
import numpy as np
from numpy import linalg as LA
import matplotlib.pyplot as plt

In [209]:
def create_stiffness_matrix(k_values):
    '''剛性マトリックス作成'''

    n = len(k_values) - 1
    k = np.zeros((n, n))

    for i in range(n):
        k[i, i] = k_values[i] + k_values[i + 1]
        if i < n - 1:
            k[i, i + 1] = -k_values[i + 1]
            k[i + 1, i] = -k_values[i + 1]

    return k

質量と剛性を入力

In [258]:
m_values = [50000, 50000, 50000]
k_values = [30000000, 20000000, 50000000, 20000000]
m_values = [1, 1]
k_values = [10, 10, 10]
f_value = [3, 1]

In [259]:
mass_matrix = np.diag(m_values)
stiffness_martix = create_stiffness_matrix(k_values)
force_vector = np.array(f_value)
mass_matrix, stiffness_martix, force_vector

(array([[1, 0],
        [0, 1]]),
 array([[ 20., -10.],
        [-10.,  20.]]),
 array([3, 1]))

固有値、固有ベクトルを計算

In [260]:
mass_matrix_inv = np.linalg.inv(mass_matrix)
eigenvalues, eigenvectors = LA.eig(np.dot(mass_matrix_inv, stiffness_martix))
eigenvalues, eigenvectors

(array([30., 10.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

In [261]:
# 固有値の順番を昇順にソート
eigenvalues_sort = np.sort(eigenvalues)
 
# 固有値のソート時のインデックスを取得
# ⇒固有ベクトルと対応させるため
sort_index = np.argsort(eigenvalues)
 
# 固有値に対応する固有ベクトルをソート
eigenvectors_sort = []
for i in range(len(sort_index)):
    eigenvectors_sort.append(eigenvectors.T[sort_index[i]])
eigenvectors_sort = np.array(eigenvectors_sort)
 
# 結果をコンソールに表示
print(np.sqrt(eigenvalues_sort))
print(eigenvectors_sort)

[3.16227766 5.47722558]
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [262]:
eigen_mode_matrix = eigenvectors_sort.T
eigen_mode_matrix

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [263]:
for i, value in enumerate(eigenvalues):
    print(f'{len(eigenvalues)-i}次 固有値 = {np.sqrt(eigenvalues)[i]:.03f} , 固有ベクトル = {eigenvectors[:, i]}')

2次 固有値 = 5.477 , 固有ベクトル = [ 0.70710678 -0.70710678]
1次 固有値 = 3.162 , 固有ベクトル = [0.70710678 0.70710678]


モード質量、モード剛性

In [255]:
modal_mass_matrix = np.dot(eigen_mode_matrix.T, np.dot(mass_matrix, eigen_mode_matrix))
modal_stiffness_matrix = np.dot(eigen_mode_matrix.T, np.dot(stiffness_martix, eigen_mode_matrix))
modal_mass_matrix, modal_stiffness_matrix

(array([[1., 0.],
        [0., 1.]]),
 array([[ 1.00000000e+01, -1.77635684e-15],
        [-8.88178420e-16,  3.00000000e+01]]))

In [257]:
modal_mass_1, modal_mass_2 = modal_mass_matrix[0][0], modal_mass_matrix[1][1]
modal_mass_1, modal_mass_2
modal_stiffness_1, modal_stiffness_2 = modal_stiffness_matrix[0][0], modal_stiffness_matrix[1][1]
modal_stiffness_1, modal_stiffness_2
modal_force_1 = 

(10.0, 30.0)